import { Button } from "std-widgets.slint";
import "res/Retron2000.ttf";

struct TranslationItem {
    key: string,
    value: string,
}

export global L10n {
    pure callback get(string) -> string;
}

component OptionsButton {
    in property <string> text;
    in property <image> icon-source;
    callback clicked;

    width: 200px;
    height: 55px;

    state-item := Rectangle {
        background: touch.pressed ? rgb(253, 255, 153) : rgb(255, 255, 255);

        border-radius: self.height / 2;

        property <float> btn-scale: 1.0;
        width: parent.width * btn-scale;
        height: parent.height * btn-scale;

        animate width, height {
            duration: 150ms;
            easing: ease-out-back;
        }
        animate background { duration: 100ms; }

        HorizontalLayout {
            padding: 10px;
            spacing: 10px;
            alignment: center;

            Image {
                source: root.icon-source;
                width: 32px;
                height: 32px;
                image-fit: contain;
            }

            Text {
                text: root.text;
                color: black;
                font-size: 18px;
                font-weight: 700;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }

    touch := TouchArea {
        clicked => { root.clicked(); }
    }

    states [
        pressed when touch.pressed : {
            state-item.btn-scale: 0.95;
        }
        hovered when touch.has-hover : {
            state-item.btn-scale: 1.05;
        }
    ]
}

component PlayButton {
    in property <string> text;
    callback clicked;

    width: 700px;
    height: 70px;

    state-item := Rectangle {
        background: touch.pressed ? rgb(138, 255, 152) : rgb(255, 255, 255);
        border-radius: 15px;

        animate background { duration: 80ms; }

        property <float> w-scale: 1.0;
        property <float> h-scale: 1.0;

        width: parent.width * self.w-scale;
        height: parent.height * self.h-scale;

        animate width, height {
            duration: 150ms;
            easing: ease-out-back;
        }

        Text {
            text: root.text;
            font-size: 36px;
            color: black;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    touch := TouchArea {
        clicked => { root.clicked(); }
    }

    states [
            pressed when touch.pressed : {
                state-item.w-scale: 0.8;
                state-item.h-scale: 0.96;
            }
            hovered when touch.has-hover : {
                state-item.w-scale: 1.33;
                state-item.h-scale: 1;
            }
        ]
}

export component MainWindow inherits Window {
    default-font-family: "Retron2000";
    width: 1080px;
    height: 720px;
    title: "Relay - SharpCraft Launcher";
    background: #2b2b2b;

    callback versions_clicked();
    callback settings_clicked();
    callback account_clicked();
    callback launch_clicked();

    // 0: Main, 1: Account, 2: Settings, 3: Versions
    in-out property <int> active-screen: 0;

    Rectangle {
        width: 100%;
        height: 100%;
        clip: true;

        main_view := VerticalLayout {
            padding: 30px;
            spacing: 40px;
            alignment: start;

            x: root.active-screen == 1 ? parent.width : (root.active-screen == 3 ? -parent.width : 0);

            y: root.active-screen == 2 ? parent.height : 0;

            animate x, y { duration: 250ms; easing: ease-in-out; }

            HorizontalLayout {
                alignment: center;
                spacing: 10px;
                OptionsButton {
                    text: L10n.get("account_btn");
                    icon-source: @image-url("res/human.svg");
                    clicked => { root.account_clicked(); }
                }
                OptionsButton {
                    text: L10n.get("settings_btn");
                    icon-source: @image-url("res/gear.svg");
                    clicked => { root.settings_clicked(); }
                }
                OptionsButton {
                    text: L10n.get("versions_btn");
                    icon-source: @image-url("res/tree.svg");
                    clicked => { root.versions_clicked(); }
                }
            }

            HorizontalLayout {
                alignment: center;
                spacing: 30px;
                Rectangle {
                    width: 650px; height: 470px; background: #ccc; border-radius: 20px;
                    Text { text: L10n.get("changes_field"); y: 10px; width: parent.width; horizontal-alignment: center; }
                }
                Rectangle {
                    width: 250px; height: 470px; background: #ccc; border-radius: 20px;
                    Text { text: L10n.get("commit_field"); y: 10px; width: parent.width; horizontal-alignment: center; }
                }
            }

            VerticalLayout {
                alignment: end;
                padding-bottom: 20px;
                HorizontalLayout {
                    alignment: center;
                    PlayButton {
                        text: L10n.get("launch_btn");
                        clicked => { root.launch_clicked(); }
                    }
                }
            }
        }

        account_view := VerticalLayout {
            x: root.active-screen == 1 ? 0 : -parent.width;
            width: 100%; height: 100%;
            animate x { duration: 250ms; easing: ease-in-out; }

            alignment: center;
            spacing: 20px;

            Text {
                text: "Account Screen";
                color: white;
                font-size: 30px;
                horizontal-alignment: center;
            }

            HorizontalLayout {
                alignment: center;
                Button {
                    text: "Back";
                    width: 100%;
                    clicked => { root.active-screen = 0; }
                }
            }
        }

        settings_view := VerticalLayout {
            y: root.active-screen == 2 ? 0 : -parent.height;
            width: 100%; height: 100%;
            animate y { duration: 250ms; easing: ease-in-out; }

            alignment: center;
            spacing: 20px;

            Text {
                text: "Settings Screen";
                color: white;
                font-size: 30px;
                horizontal-alignment: center;
            }

            HorizontalLayout {
                alignment: center;
                Button {
                    text: "Back";
                    width: 100%;
                    clicked => { root.active-screen = 0; }
                }
            }
        }

        versions_view := VerticalLayout {
            x: root.active-screen == 3 ? 0 : parent.width;
            width: 100%; height: 100%;
            animate x { duration: 250ms; easing: ease-in-out; }

            alignment: center;
            spacing: 20px;

            Text {
                text: "Versions Screen";
                color: white;
                font-size: 30px;
                horizontal-alignment: center;
            }

            HorizontalLayout {
                alignment: center;
                Button {
                    text: "Back";
                    width: 100%;
                    clicked => { root.active-screen = 0; }
                }
            }
        }
    }
}